data_ingestion:
  kaggle_source: "nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone"
  download_path: artifacts/data_ingestion


base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.keras
  updated_base_model_path: artifacts/base_model/base_model_updated.keras



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras
  training_data: artifacts\data_ingestion\datasets\\nazmul0087\ct-kidney-dataset-normal-cyst-tumor-and-stone\\versions\\1\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone\CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
